odin-kittens/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#search'

  match '/search', to: 'static_pages#search', via: 'get'

  resources :kittens

end

odin-kittens/app/models/kitten.rb
class Kitten < ActiveRecord::Base
	
end

odin-kittens/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

odin-kittens/app/controllers/kittens_controller.rb
class KittensController < ApplicationController
	def index
		@kittens = Kitten.all
		respond_to do |format|
			format.html
			format.json { render json: @kittens }
		end
		
	end

	def show
		@kitten = Kitten.find(params[:id])
		respond_to do |format|
			format.html
			format.json { render json: @kitten }
		end
	end

	def new
		@kitten = Kitten.new
	end

	def create
		@kitten = Kitten.new(kitten_params)
		if @kitten.save
			flash[:success] = "your kitten has been successfully purchased"
			redirect_to kittens_path
		else
			render 'new'
		end
	end

	def edit
		@kitten = Kitten.find(params[:id])
	end

	def update
		@kitten = Kitten.find(params[:id])
		if @kitten.update_attributes(kitten_params)
			redirect_to kitten_path(@kitten)
		else
			render 'edit'
		end

	end

	def destroy
		@kitten = Kitten.find(params[:id])
		if @kitten.destroy
			flash[:success] = "bye bye kitten, it was nice knowing you"
			redirect_to kittens_path
		end
	end

	private
		def kitten_params
			params.require(:kitten).permit(:name, :age, :cuteness, :softness)
		end

		

end

odin-kittens/app/controllers/static_pages_controller.rb
require 'pry'

class StaticPagesController < ApplicationController

include FlickrHelper
	
	def search
		@tag = params[:keyword]
		if @tag
			FlickRaw.api_key = "130febb7f18e782fd3b1461448969d0d"
			FlickRaw.shared_secret = "d04802d8e91b6d35"
			results = cat_search(@tag)
			index = Random.rand(0...100)
			@url = cat_photo(results[index]["id"])
		end
	end
end

odin-kittens/app/helpers/application_helper.rb
module ApplicationHelper
end

odin-kittens/app/helpers/flickr_helper.rb
require 'flickraw'

module FlickrHelper

	def cat_search(tag)
		return flickr.photos.search(tags: tag)
	end

	def cat_photo(photo_id)
		info = flickr.photos.getInfo(photo_id: photo_id)
		return FlickRaw.url_b(info)
	end
end

odin-kittens/app/helpers/kittens_helper.rb
module KittensHelper
end

odin-kittens/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

odin-kittens/app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= form_for @kitten do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :age %>
		<%= f.text_field :age, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :cuteness %>
		<%= f.text_field :cuteness, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :softness %>
		<%= f.text_field :softness, class: "form-control" %>
	</div>

	<div class="submit">
		<%= f.submit "Update", class: "btn btn-primary btn-lg" %>
 	</div>
<% end %>

odin-kittens/app/views/kittens/index.html.erb
<h1>My Kittens</h1>

<% flash.each do |key, value| %>
	<%= content_tag :div, value, class: "flash #{key}" %>
<% end %>
<ul>
	<% for kitten in @kittens %>
		<li><%= kitten.inspect %></li>
		<%= link_to "Edit", edit_kitten_path(kitten) %> |
		<%= link_to "Delete", kitten, method: :delete, data: { confirm: "You sure?" } %>
	<% end %>
</ul>

odin-kittens/app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= form_for @kitten do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :age %>
		<%= f.text_field :age, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :cuteness %>
		<%= f.text_field :cuteness, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :softness %>
		<%= f.text_field :softness, class: "form-control" %>
	</div>

	<div class="submit">
		<%= f.submit "Update", class: "btn btn-primary btn-lg" %>
 	</div>
<% end %>

odin-kittens/app/views/kittens/show.html.erb
<h1>Show Kitten</h1>

<ul>
<%= @kitten.inspect %>
</ul>

<%= link_to "Delete", @kitten, method: :delete, data: { confirm: "You sure?" } %>

odin-kittens/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

odin-kittens/app/views/static_pages/search.html.erb
<h1>Search for keywords</h1>

<%= form_tag("/search", method: "get") do %>
	<%= label_tag(:keyword, "Search for:") %>
	<%= text_field_tag(:keyword,  params[:keyword], placeholder: "kittens") %>
	<%= submit_tag("Search") %>
<% end %>

<% if @url %>
	<%= image_tag(@url) %>
<% end %>